services:
  navigation:
    container_name: turtlebot3-docker
    image: ghcr.io/collaborativeroboticslab/turtlebot3-docker:humble
    command: ["ros2", "launch", "system-with-sim.launch", "slam:=true"]
    restart: unless-stopped
    privileged: true
    network_mode: host
