services:
  turtlebot3-docker:
    container_name: turtlebot3-docker
    build:
      dockerfile: Dockerfile
    command: ["ros2", "launch", "system-with-sim.launch", "slam:=true"]
    restart: unless-stopped
    privileged: true
    network_mode: host
